name: 'Build Commit'
on:
  push:
    branches:
      - 'main'
    paths-ignore:
      - '*.md'
      - 'LICENSE'

jobs:
  build:
    uses: MinecraftschurliMods/.github/.github/workflows/build-library.yml@main
    with:
      java-version: 21
      maven-url: ${{ vars.MAVEN_URL }}
      maven-user: ${{ vars.MAVEN_USER }}
      publish-to-maven: true
    secrets:
      MAVEN_PASSWORD: ${{ secrets.MAVEN_PASSWORD }}
