name: 'Build PR'

on:
  pull_request:
    paths-ignore:
      - '*.md'
      - 'LICENSE'
      - '.github/**'

jobs:
  build:
    uses: MinecraftschurliMods/.github/.github/workflows/build-library.yml@main
